package URLReaderApp;


/**
* URLReaderApp/URLReader.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from urlreader.idl
* Tuesday, May 10, 2022 8:32:05 PM IST
*/

public interface URLReader extends URLReaderOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface URLReader
