package MultiplyApp;


/**
* MultiplyApp/MultiplyPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Multiply.idl
* Monday, May 9, 2022 5:33:32 PM IST
*/

public abstract class MultiplyPOA extends org.omg.PortableServer.Servant
 implements MultiplyApp.MultiplyOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("multiply", new java.lang.Integer (0));
    _methods.put ("shutdown", new java.lang.Integer (1));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // MultiplyApp/Multiply/multiply
       {
         int a = in.read_long ();
         int b = in.read_long ();
         int $result = (int)0;
         $result = this.multiply (a, b);
         out = $rh.createReply();
         out.write_long ($result);
         break;
       }

       case 1:  // MultiplyApp/Multiply/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:MultiplyApp/Multiply:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Multiply _this() 
  {
    return MultiplyHelper.narrow(
    super._this_object());
  }

  public Multiply _this(org.omg.CORBA.ORB orb) 
  {
    return MultiplyHelper.narrow(
    super._this_object(orb));
  }


} // class MultiplyPOA
