package MultiplyApp;

/**
* MultiplyApp/MultiplyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Multiply.idl
* Monday, May 9, 2022 5:33:32 PM IST
*/

public final class MultiplyHolder implements org.omg.CORBA.portable.Streamable
{
  public MultiplyApp.Multiply value = null;

  public MultiplyHolder ()
  {
  }

  public MultiplyHolder (MultiplyApp.Multiply initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = MultiplyApp.MultiplyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    MultiplyApp.MultiplyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return MultiplyApp.MultiplyHelper.type ();
  }

}
