package MultiplyApp;


/**
* MultiplyApp/MultiplyHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Multiply.idl
* Monday, May 9, 2022 5:33:32 PM IST
*/

abstract public class MultiplyHelper
{
  private static String  _id = "IDL:MultiplyApp/Multiply:1.0";

  public static void insert (org.omg.CORBA.Any a, MultiplyApp.Multiply that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static MultiplyApp.Multiply extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (MultiplyApp.MultiplyHelper.id (), "Multiply");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static MultiplyApp.Multiply read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_MultiplyStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, MultiplyApp.Multiply value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static MultiplyApp.Multiply narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MultiplyApp.Multiply)
      return (MultiplyApp.Multiply)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MultiplyApp._MultiplyStub stub = new MultiplyApp._MultiplyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static MultiplyApp.Multiply unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof MultiplyApp.Multiply)
      return (MultiplyApp.Multiply)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      MultiplyApp._MultiplyStub stub = new MultiplyApp._MultiplyStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
