package MultiplyApp;


/**
* MultiplyApp/Multiply.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Multiply.idl
* Monday, May 9, 2022 5:33:32 PM IST
*/

public interface Multiply extends MultiplyOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Multiply
