package MultiplyApp;


/**
* MultiplyApp/MultiplyOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Multiply.idl
* Monday, May 9, 2022 5:33:32 PM IST
*/

public interface MultiplyOperations 
{
  int multiply (int a, int b);
  void shutdown ();
} // interface MultiplyOperations
